### ISSUE TITLE
[PullRequest] Some improvments / features

### ISSUE THREAD

**Issue by JanLoebel** [niklaskappler/MMM-vvsDeparture#2]
Hi there,

first of all, thanks for the greate module. I've had a look into it and refactored some of the code :) Furthermore, I've added some new configuration properties to the module. With them, you can easily configure if delays or "no delays" should be colorized and hide some unwanted lane numbers or directions. 

The module is missing a license, perhaps you should add that :)

If you have any questions or suggestions about the pull-request, please feel free to contact me!

Jan

**Comment by niklaskappler** [comment]
Hi Jan, 

thanks for your contribution & improvements. Jeah it was written ferry fast and dirty. Licence added. Thanks a lot for your work
