### ISSUE TITLE
module does not work anymore

### ISSUE THREAD

**Issue by Edisos** [niklaskappler/MMM-vvsDeparture#4]
I used the module for several month but since today it does not work anymore. 

Are there any updates necessary or is there a problem with the api?

**Comment by niklaskappler** [comment]
Hi, jeah youre right. Is seems that the VVS is shutting down the old API the module is running on. I already checked the version 2 of the VVS api. 
Currently I have not time to upgrade the module. I planned to work on the module over christmas.

**Comment by niklaskappler** [comment]
I fixed the the problem and created a new release. ([v1.2](https://github.com/niklaskappler/MMM-vvsDeparture/tree/v1.2))
