### ISSUE TITLE
Needs option to specify platform

### ISSUE THREAD

**Issue by akraus53** [niklaskappler/MMM-vvsDeparture#8]
Often, you're happy with anything that goes into the right direction...

**Comment by niklaskappler** [comment]
Hi @akraus53, 
cloud you be more precise in what exactly which problem you wan't to adress with this issue. And how others may also profit from this. 
Btw. there is already an option to specify the directions, if you check the config options.

**Comment by akraus53** [comment]
I'm sorry, I thought it was clear enough. 

If you live in an area like Vaihingen and you want your mirror to show you departures toward city center, it's tedious to enter all the lanes when you could simply add "all departures from platform 3" which I think all go toward Stuttgart. You wouldn't have to add Kirchheim and Plochingen separately, because the S1 alernates between those destinations. If you think it's a hassle to add, it's fine, the workaround is obvious, but I think it would be a nice feature.

**Comment by akraus53** [comment]
Closing because I really don't care anymore ;)
