### ISSUE TITLE
Modul funktioniert nicht & Hinweis zur API

### ISSUE THREAD

**Issue by chris-kwl** [niklaskappler/MMM-vvsDeparture#9]
Hi,
leider bekomme das Modul bei mir nicht zum laufen, sehe lediglich "Abfahrten von undefined".
Ich denke das liegt daran das die Ausgabe sich geändert hat, die Abfragen an sich funktionieren noch.

Habe mehrere Configs probiert, immer mit dem oben genannten Ergebnis, unter andrem diese (Charlottenplatz):
`	{
		module: 'MMM-vvsDeparture',
		position: "bottom_left",
		config: {
			station_id: '6075',
		}
	},`

Abgesehen davon habe ich mir mal die API angeguckt und festgestellt das mit anstelle der StationID auch den Namen verwenden kann. Am obigen Beispiel: Anstatt `name_dm=6075` einfach `typeInfo_dm=stopID&nameInfo_dm=Charlottenplatz`

Darauf gekommen bin ich über dieses Repo: https://github.com/stz-online/OpenVVSDay
Dort wird anstelle von `https://www3.vvs.de/mngvvs/` zwar `http://efastatic.vvs.de/OpenVVSDay/` verwendet, die Funktionen sind aber identisch. Auch ist dort eine Dokumentation und eine API für Verbindungsauskünfte genannt. Könnte für eine Erweiterung der Funktionalität und unter anderem für #7 interessant sein.

**Comment by chris-kwl** [comment]
Konnte das Problem durch Neuaufsetzen von von MM lösen, komischerweise liefen alle anderen Module aber noch problemlos.
Dabei ist mir gerade noch auf gefallen das der station_id scheinbar irgendwo nicht gelöscht wird, habe die ID gerade mehrfach geändert und jetzt wechselt die Ansicht gefühlt alle 10 Sekunden die Station, inkl. Abfahrten. Finde das zur Visualisierung mehrerer Stationen gar nicht schlecht, soll aber sicher nicht das Normalverhalten sein.
Ansonsten funktioniert das Modul jetzt aber bestens :)

Lasse den Fehler bzgl. des API Hinweises mal offen, kann aber gerne geschlossen werden.

**Comment by niklaskappler** [comment]
Hi @chris-kwl, 
vielen Dank für dein Interesse and dem Modul. Erstmal super wenn sich dein Problem von selbst gelöst hat. Das von dir beschreiben Verhalten schein mir etwas flaky, hast du versucht die MM-Software neu zu starten? Evtl. hat das "Hot-Reloaden" der config sich verhaspelt. 

Bzgl. der API Änderung: Ich würde es vorziehen den Endpunkt weiter zu nutzen. Der von dir vorgeschlagene Endpunkt wirkt für mich sehr and diesen OpenVVS Day gebunden. Ich bin mir tatsächlich auch nicht sicher ob darüber alle Infos auch wirklich bereitgestellt werden. I.d.R hab die sämtliche Verkehrsbetriebe immer sehr bedacht wahrgenommen was Zugang zu Daten angeht. Die Möglichkeit die Daten mit dem Parameter `nameInfo_dm` abzufragen verspricht verlockend zu sein und ist auch über die  `https://www3.vvs.de/mngvvs/[...]` möglich, liefert allerdings nicht immer die exakte Station beziehungsweise die Abfahrten für die Station zurück sondern unter umständen die POIs die das VVS System kennt welche auf den gegebenen Begriff passen. Da der derzeitig verwendete Endpunkt derselbe ist den auch die App und die Suche auf der offiziellen VVS Seite benutz würde ich unter anderem hinsichtlich Stabilität den Endpunkt beibehalten. Tausend Dank dennoch für den Hinweis.
